In [13]:
REPO <- "https://raw.githubusercontent.com/andrecesar00/predicarga_andre_diego_kaykhy/main/"

source("https://raw.githubusercontent.com/fractalarea/pi3-motor-de-busca/main/motor/motor05b.R")

download.file(paste0(REPO, "estrutura/codigo/config.R"), "config.R")
source("config.R")

cp <- read.csv(paste0(REPO, "estrutura/banco-de-dados/corpus.csv"),
               stringsAsFactors = FALSE, fileEncoding = "UTF-8")

docs <- setNames(cp$texto, cp$id)

origem <- readRDS(gzcon(url(paste0(REPO, "estrutura/banco-de-dados/origem.rds"))))

ix <- montar(docs, cfg)

estado()

<!-- estado-R:inicio -->
## Estado do R ao fim da sessão
*gerado por `anexar_estado()` em 2026-10-25 18:07 · R version 4.6.1 (2026-06-24) · motor05b v1 2026-10-01 · não edite à mão*

### Objetos

| objeto | tipo | tamanho | valor / amostra |
|---|---|---|---|
| `cfg$minimo` | numeric | 1 | 200 |
| `cfg$limpar` | logical | 1 | TRUE |
| `cfg$acentos` | character | 1 | translit |
| `cfg$stopwords` | character | 12 | de, e, a, o, em, da, ... |
| `cfg$grupo` | character | 1 | Predicarga |
| `cp` | data.frame | 64 × 5 | colunas: id, titulo, texto, fonte, url |
| `docs` | character, nomeado | 64 | d1 São Vicente, oficialmente E..., d2 São Vicente marca o início ..., d3 Com um PIB de mais de 6 bil..., d4 São Vicente preserva divers..., d5 A Ilha de Gohayó foi descob..., d6 Nas primeiras décadas do sé..., ... |
| `ix$tokens` | list | 64 | elementos: d1, d2, d3, d4, d5, d6, d7, d8, ... |
| `ix$vocab` | character | 1831 | 0, 01, 0132, 06, 1, 100, ... |
| `ix$tf` | matrix | 1831 × 64 | linhas: 0, 01, 0132, ... \| colunas: d1, d2, d3, d4, ... |
| `ix$N` | integer | 1 | 64 |
| `ix$df` | numeric, nomeado | 1831 | 0 1, 01 1, 0132 1, 06 1, 1 4, 100 1, ... |
| `ix$idf_tfidf` | numeric, nomeado | 1831 | 0 4.159, 01 4.159, 0132 4.159, 06 4.159, 1 2.773, 100 4.159, ... |
| `ix$w` | matrix | 1831 × 64 | linhas: 0, 01, 0132, ... \| colunas: d1, d2, d3, d4, ... |
| `ix$wn` | matrix | 1831 × 64 | linhas: 0, 01, 0132, ... \| colunas: d1, d2, d3, d4, ... |
| `ix$postings` | list | 1831 | elementos: sao, vicente, oficialmente, estancia, balnearia, um, municipio, brasileiro, ... |
| `ix$dl` | numeric, nomeado | 64 | d1 58, d2 127, d3 109, d4 152, d5 27, d6 74, ... |
| `ix$avgdl` | numeric | 1 | 62.75 |
| `ix$idf_bm25` | numeric, nomeado | 1831 | 0 3.769, 01 3.769, 0132 3.769, 06 3.769, 1 2.67, 100 3.769, ... |
| `MOTOR_VERSAO` | character | 1 | motor05b v1 2026-10-01 |
| `origem` | character, nomeado | 64 | d1 São Vicente (São Paulo), d2 São Vicente (São Paulo), d3 São Vicente (São Paulo), d4 São Vicente (São Paulo), d5 São Vicente (São Paulo), d6 São Vicente (São Paulo), ... |
| `REPO` | character | 1 | https://raw.githubuserconte... |

### Funções definidas

`anexar_estado`, `bm25`, `bm25_doc`, `busca_AND`, `busca_booleana`, `cfg_aula`, `cosseno`, `docs_aula`, `estado`, `gabarito_aula`, `idf_bm25`, `idf_classico`, `indice_invertido`, `kappa_cohen`, `kappa_matriz`, `ler_qrels`, `limpar`, `matriz_tf`, `montar`, `norm_cols`, `preparar`, `ranking_bm25`, `ranking_cosseno`, `saturacao`, `sem_stop`, `stopwords_aula`, `tokenizar`, `vetor_consulta`
<!-- estado-R:fim -->

In [14]:
estado()

<!-- estado-R:inicio -->
## Estado do R ao fim da sessão
*gerado por `anexar_estado()` em 2026-10-25 18:07 · R version 4.6.1 (2026-06-24) · motor05b v1 2026-10-01 · não edite à mão*

### Objetos

| objeto | tipo | tamanho | valor / amostra |
|---|---|---|---|
| `cfg$minimo` | numeric | 1 | 200 |
| `cfg$limpar` | logical | 1 | TRUE |
| `cfg$acentos` | character | 1 | translit |
| `cfg$stopwords` | character | 12 | de, e, a, o, em, da, ... |
| `cfg$grupo` | character | 1 | Predicarga |
| `cp` | data.frame | 64 × 5 | colunas: id, titulo, texto, fonte, url |
| `docs` | character, nomeado | 64 | d1 São Vicente, oficialmente E..., d2 São Vicente marca o início ..., d3 Com um PIB de mais de 6 bil..., d4 São Vicente preserva divers..., d5 A Ilha de Gohayó foi descob..., d6 Nas primeiras décadas do sé..., ... |
| `ix$tokens` | list | 64 | elementos: d1, d2, d3, d4, d5, d6, d7, d8, ... |
| `ix$vocab` | character | 1831 | 0, 01, 0132, 06, 1, 100, ... |
| `ix$tf` | matrix | 1831 × 64 | linhas: 0, 01, 0132, ... \| colunas: d1, d2, d3, d4, ... |
| `ix$N` | integer | 1 | 64 |
| `ix$df` | numeric, nomeado | 1831 | 0 1, 01 1, 0132 1, 06 1, 1 4, 100 1, ... |
| `ix$idf_tfidf` | numeric, nomeado | 1831 | 0 4.159, 01 4.159, 0132 4.159, 06 4.159, 1 2.773, 100 4.159, ... |
| `ix$w` | matrix | 1831 × 64 | linhas: 0, 01, 0132, ... \| colunas: d1, d2, d3, d4, ... |
| `ix$wn` | matrix | 1831 × 64 | linhas: 0, 01, 0132, ... \| colunas: d1, d2, d3, d4, ... |
| `ix$postings` | list | 1831 | elementos: sao, vicente, oficialmente, estancia, balnearia, um, municipio, brasileiro, ... |
| `ix$dl` | numeric, nomeado | 64 | d1 58, d2 127, d3 109, d4 152, d5 27, d6 74, ... |
| `ix$avgdl` | numeric | 1 | 62.75 |
| `ix$idf_bm25` | numeric, nomeado | 1831 | 0 3.769, 01 3.769, 0132 3.769, 06 3.769, 1 2.67, 100 3.769, ... |
| `MOTOR_VERSAO` | character | 1 | motor05b v1 2026-10-01 |
| `origem` | character, nomeado | 64 | d1 São Vicente (São Paulo), d2 São Vicente (São Paulo), d3 São Vicente (São Paulo), d4 São Vicente (São Paulo), d5 São Vicente (São Paulo), d6 São Vicente (São Paulo), ... |
| `REPO` | character | 1 | https://raw.githubuserconte... |

### Funções definidas

`anexar_estado`, `bm25`, `bm25_doc`, `busca_AND`, `busca_booleana`, `cfg_aula`, `cosseno`, `docs_aula`, `estado`, `gabarito_aula`, `idf_bm25`, `idf_classico`, `indice_invertido`, `kappa_cohen`, `kappa_matriz`, `ler_qrels`, `limpar`, `matriz_tf`, `montar`, `norm_cols`, `preparar`, `ranking_bm25`, `ranking_cosseno`, `saturacao`, `sem_stop`, `stopwords_aula`, `tokenizar`, `vetor_consulta`
<!-- estado-R:fim -->

In [15]:
cfg <- list(
  minimo = 200,
  limpar = TRUE,
  acentos = "translit",
  stopwords = c("de", "e", "a", "o", "em", "da", "do",
                "que", "foi", "no", "para", "com"),
  grupo = "Predicarga",
  k1 = 1.2,
  b = 0.75
)

In [16]:
source("config.R")
cfg$k1
cfg$b

NULL

NULL

In [17]:
readLines("config.R")

[1] "cfg <- list("
[2] "  minimo = 200,"
[3] "  limpar = TRUE,"
[4] "  acentos = \"translit\","
[5] "  stopwords = c(\"de\", \"e\", \"a\", \"o\", \"em\", \"da\", \"do\","
[6] "                \"que\", \"foi\", \"no\", \"para\", \"com\"),"
[7] "  grupo = \"Predicarga\""
[8] ")"

In [18]:
source("config.R")
cfg$k1
cfg$b
readLines("config.R")

[1] 1.2

[1] 0.75

Warning message in readLines("config.R"):
“incomplete final line found on 'config.R'”

 [1] "cfg <- list("
 [2] "  minimo = 200,"
 [3] "  limpar = TRUE,"
 [4] "  acentos = \"translit\","
 [5] "  stopwords = c(\"de\", \"e\", \"a\", \"o\", \"em\", \"da\", \"do\","
 [6] "                \"que\", \"foi\", \"no\", \"para\", \"com\"),"
 [7] "  grupo = \"Predicarga\","
 [8] "  k1 = 1.2,"
 [9] "  b = 0.75"
[10] ")"

In [19]:
arqs <- c("qrels_Andre_2026-10-25.csv")

for (a in arqs)
  download.file(paste0(REPO, "estrutura/banco-de-dados/", a), a)

list.files()

qrels <- ler_qrels(arqs, juiz = cfg$juizes)

[1] "config.R"                   "qrels_Andre_2026-10-25.csv"
[3] "sample_data"

In [20]:
qrels <- ler_qrels(arqs, juiz = cfg$juizes)

names(qrels)
lengths(qrels)

[1] "q01" "q02" "q03" "q04" "q05"

q01 q02 q03 q04 q05
  1   5   2   6   7

In [21]:
nec <- read.csv(paste0(REPO, "estrutura/banco-de-dados/necessidades.csv"),
                stringsAsFactors = FALSE, fileEncoding = "UTF-8-BOM")

consultas <- setNames(nec$texto_consulta, nec$consulta)
consultas[names(qrels)]

                                           q01
                "monumentos historicos centro"
                                           q02
                 "fundacao vila martim afonso"
                                           q03
                    "ponte pensil arquitetura"
                                           q04
            "ataques piratas baixada santista"
                                           q05
"primeiros habitantes colonizacao sao vicente"

In [22]:
table(qrels[[1]])
table(qrels[[2]])
table(qrels[[3]])
table(qrels[[4]])
table(qrels[[5]])

2
1

1 2
3 2

1
2

1 2
3 3

0 1 2
1 2 4

In [23]:
source("config.R")
cfg$limiar

[1] 1

In [24]:
R_q <- sapply(qrels, function(g) sum(g >= cfg$limiar))
R_q

usar <- names(qrels)[R_q > 0]
usar

sum(!names(qrels[[1]]) %in% names(docs))

q01 q02 q03 q04 q05
  1   5   2   6   6

[1] "q01" "q02" "q03" "q04" "q05"

[1] 0

In [25]:
precisao_k <- function(rel, k) sum(rel[1:k]) / k

ap <- function(rel, R) {
  if (R == 0) return(NA)
  p <- cumsum(rel) / seq_along(rel)
  sum(p[rel == 1]) / R
}

rr <- function(rel) {
  if (sum(rel) == 0) return(0)
  1 / which(rel == 1)[1]
}

dcg <- function(g) sum(g / log2(seq_along(g) + 1))

ndcg <- function(g) {
  ideal <- sort(g, decreasing = TRUE)
  if (dcg(ideal) == 0) return(NA)
  dcg(g) / dcg(ideal)
}

In [26]:
ix_aula <- montar(docs_aula(), cfg_aula())
q_aula  <- "modelo de recuperacao"

bm <- metricas(ranking_bm25(q_aula, ix_aula, cfg_aula()), gabarito_aula(), 2)
cs <- metricas(ranking_cosseno(q_aula, ix_aula, cfg_aula()), gabarito_aula(), 2)

round(rbind(cosseno = cs, BM25 = bm), 3)

ERROR: Error in metricas(ranking_bm25(q_aula, ix_aula, cfg_aula()), gabarito_aula(), : could not find function "metricas"

In [27]:
metricas <- function(ranking, grau, limiar, k = 3) {
  g <- grau[names(ranking)]
  g[is.na(g)] <- 0
  rel <- as.integer(g >= limiar)
  R   <- sum(grau >= limiar)
  c(P_at_k = precisao_k(rel, k),
    AP = ap(rel, R),
    RR = rr(rel),
    nDCG_bin = ndcg(rel),
    nDCG_grad = ndcg(g))
}

In [28]:
ix_aula <- montar(docs_aula(), cfg_aula())
q_aula  <- "modelo de recuperacao"

bm <- metricas(ranking_bm25(q_aula, ix_aula, cfg_aula()), gabarito_aula(), 2)
cs <- metricas(ranking_cosseno(q_aula, ix_aula, cfg_aula()), gabarito_aula(), 2)

round(rbind(cosseno = cs, BM25 = bm), 3)

        P_at_k AP    RR  nDCG_bin nDCG_grad
cosseno 0.333  0.500 0.5 0.651    0.837
BM25    0.667  0.833 1.0 0.920    0.951

In [29]:
q   <- usar[1]
txt <- consultas[[q]]

bm <- metricas(ranking_bm25(txt, ix, cfg), qrels[[q]], cfg$limiar)
cs <- metricas(ranking_cosseno(txt, ix, cfg), qrels[[q]], cfg$limiar)

round(rbind(cosseno = cs, BM25 = bm), 3)

        P_at_k AP    RR    nDCG_bin nDCG_grad
cosseno 0      0.023 0.023 0.183    0.183
BM25    0      0.023 0.023 0.183    0.183

In [30]:
names(ranking_bm25(consultas[[q]], ix, cfg))[1:5]
names(ranking_cosseno(consultas[[q]], ix, cfg))[1:5]

[1] "d6" "d2" "d4" "d1" "d3"

[1] "d6" "d2" "d4" "d1" "d3"

In [31]:
qrels[[q]]

d43
  2

In [32]:
docs[["d43"]]
origem[["d43"]]

[1] "Já em 1533 se encontrava em Portugal. Então no dia 19 de dezembro de 1533, passados quatro meses desde que tinha voltado de sua cansativa viagem, D. João III mandou-o servir na Índia com o posto de Capitão-Mor do mar Índico. Para o efeito, foi-lhe confiado o governo de uma Armada de cinco naus. Segundo o cronista Gaspar Correia, em Lendas da Índia, \"Martim Afonso muito se enojou da decisão, porque sentiu que isso vinha por D. António\"."

[1] "Martim Afonso de Sousa"

In [33]:
c("monumentos", "historicos", "centro") %in% unlist(strsplit(docs[["d43"]], " "))

[1] FALSE FALSE FALSE

In [34]:
tab_bm <- sapply(usar, function(q)
  metricas(ranking_bm25(consultas[[q]], ix, cfg), qrels[[q]], cfg$limiar))

tab_cos <- sapply(usar, function(q)
  metricas(ranking_cosseno(consultas[[q]], ix, cfg), qrels[[q]], cfg$limiar))

round(tab_bm - tab_cos, 3)

          q01 q02   q03 q04 q05
P_at_k    0   0.000 0   0    0.000
AP        0   0.023 0   0   -0.001
RR        0   0.117 0   0    0.000
nDCG_bin  0   0.040 0   0   -0.002
nDCG_grad 0   0.025 0   0   -0.002

In [35]:
round(rbind(BM25 = rowMeans(tab_bm), cosseno = rowMeans(tab_cos)), 3)

rbind(BM25    = rowSums(tab_bm > tab_cos),
      cosseno = rowSums(tab_cos > tab_bm))

        P_at_k AP    RR    nDCG_bin nDCG_grad
BM25    0      0.077 0.099 0.316    0.298
cosseno 0      0.072 0.075 0.309    0.293

        P_at_k AP RR nDCG_bin nDCG_grad
BM25    0      1  1  1        1
cosseno 0      1  0  1        1

In [36]:
list.files()

[1] "00_FICHA_PROJETO.md"           "aula05b_parteD_consolidado.md"
[3] "config.R"                      "qrels_Andre_2026-10-25.csv"
[5] "sample_data"

In [37]:
anexar_estado("00_FICHA_PROJETO.md")
anexar_estado("aula05b_parteD_consolidado.md")

Estado do R anexado a 00_FICHA_PROJETO.md (55 linhas de objetos).

Estado do R anexado a aula05b_parteD_consolidado.md (55 linhas de objetos).